version: "3.3"
services:
  keycloak:
    # image: jboss/keycloak
    image: gunnaraccso/keycloak.server:10.0.1
    ports:
      - 9000:8080
    environment:
      - TEST=1
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
